apiVersion: v2
name: birthday-app
description: HTTP API that stores a user's date of birth and returns a birthday countdown message.
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Henry Dominguez
keywords:
  - birthday
  - titanos
  - kong
