{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "birthday-app.serviceAccountName" . }}
  labels:
    {{- include "birthday-app.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
