apiVersion: v1
kind: Service
metadata:
  name: {{ include "birthday-app.fullname" . }}
  labels:
    {{- include "birthday-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "birthday-app.appSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
